name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew assembleJar

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name == 'push' }}
      with:
        tag_name:  ${{ github.run_number }}
        files: build/libs/extension-tester.jar
